[2025-05-27 23:17:31.082] ERROR: invalid destination language | Context: Critical error in main loop
[2025-05-28 00:19:53.407] ERROR: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) | Context: Critical error in main loop
[2025-06-01 18:28:30.563] ERROR: 'id' | Context: Critical error in main loop
[2025-06-01 18:28:38.581] ERROR: 'id' | Context: Critical error in main loop
[2025-06-01 18:28:46.059] ERROR: 'id' | Context: Critical error in main loop
[2025-06-01 18:28:53.551] ERROR: 'id' | Context: Critical error in main loop
[2025-06-01 19:10:51.118] ERROR: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) | Context: Critical error in main loop
[2025-06-01 19:13:45.341] ERROR: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) | Context: Critical error in main loop
[2025-06-01 20:37:21.898] ERROR: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) | Context: Critical error in main loop
[2025-06-01 21:37:16.196] ERROR: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) | Context: Critical error in main loop
[2025-06-02 04:33:52.507] ERROR: local variable 'shared_dict_id' referenced before assignment | Context: Critical error in main loop
[2025-06-02 04:35:21.822] ERROR: local variable 'shared_dict_id' referenced before assignment | Context: Critical error in main loop
[2025-06-02 04:37:12.524] ERROR: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) | Context: Critical error in main loop
[2025-06-02 04:44:04.095] ERROR: local variable 'db_manager' referenced before assignment | Context: Critical error in main loop
[2025-06-02 04:44:10.116] ERROR: local variable 'db_manager' referenced before assignment | Context: Critical error in main loop
[2025-06-02 04:49:48.245] ERROR: local variable 'db_manager' referenced before assignment | Context: Critical error in main loop
[2025-06-02 04:51:26.477] ERROR: local variable 'db_manager' referenced before assignment | Context: Critical error in main loop
[2025-06-02 04:57:39.104] ERROR: local variable 'db_manager' referenced before assignment | Context: Critical error in main loop
[2025-06-02 05:02:18.886] ERROR: local variable 'db_manager' referenced before assignment | Context: Critical error in main loop
[2025-06-02 05:37:11.010] ERROR: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) | Context: Critical error in main loop
[2025-06-02 05:58:39.905] ERROR: database is locked | Context: Critical error in main loop
[2025-06-02 06:37:20.634] ERROR: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) | Context: Critical error in main loop
[2025-06-02 07:37:16.878] ERROR: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) | Context: Critical error in main loop
[2025-06-02 16:37:29.347] ERROR: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25) | Context: Critical error in main loop
[2025-06-03 08:23:22.577] ERROR: name 'clear_state' is not defined | Context: Critical error in main loop
[2025-06-03 08:23:37.693] ERROR: name 'clear_state' is not defined | Context: Critical error in main loop
[2025-06-03 08:24:37.879] ERROR: name 'clear_state' is not defined | Context: Critical error in main loop
[2025-06-03 08:24:43.913] ERROR: name 'clear_state' is not defined | Context: Critical error in main loop
[2025-06-04 01:59:14.655] ERROR: no such table: possessive_articles | Context: Critical error in main loop
[2025-06-04 01:59:30.006] ERROR: no such table: possessive_articles | Context: Critical error in main loop
[2025-06-06 20:52:09.613] ERROR: no such table: user_871307030 | Context: Critical error in main loop
[2025-06-09 09:02:55.140] ERROR: Scheduler is not running | Context: Critical error in main loop
[2025-06-09 09:03:19.192] ERROR: Scheduler is not running | Context: Critical error in main loop
[2025-06-09 09:03:43.247] ERROR: Scheduler is not running | Context: Critical error in main loop
[2025-06-09 09:09:01.150] ERROR: Scheduler is not running | Context: Critical error in main loop
[2025-06-09 10:07:46.968] ERROR: Critical error: local variable 'traceback' referenced before assignment | Context: Critical error in main loop
[2025-06-09 10:46:18.110] ERROR: name 'db_manager' is not defined | Context: Critical error in main loop
[2025-06-09 10:46:24.125] ERROR: name 'db_manager' is not defined | Context: Critical error in main loop
[2025-06-09 10:46:51.010] ERROR: cannot import name 'get_localized_text' from 'utils.language_utils' (C:\Users\whyfl\Desktop\2025-05-27_15-35-46\utils\language_utils.py) | Context: Critical error in main loop
[2025-06-09 11:30:02.017] ERROR: 'dict' object has no attribute 'text' | Context: Critical error in main loop
[2025-06-09 11:30:23.324] ERROR: 'dict' object has no attribute 'text' | Context: Critical error in main loop
[2025-06-09 11:30:29.344] ERROR: 'dict' object has no attribute 'text' | Context: Critical error in main loop
[2025-06-09 11:35:20.908] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:35:27.233] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:35:33.472] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:35:39.703] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:35:45.943] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:35:52.159] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:35:58.359] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:36:04.601] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:36:10.786] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:36:16.983] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:36:23.157] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:36:29.385] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:36:35.556] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:36:41.766] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:36:47.942] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:36:54.153] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:37:00.382] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:37:06.656] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:37:12.900] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:37:19.140] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:37:25.381] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:37:31.626] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:37:37.859] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:37:44.078] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:37:50.306] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:37:56.540] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:38:02.757] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:38:09.000] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:38:15.220] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:38:21.429] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:38:27.636] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:38:33.822] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:38:40.078] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:38:46.298] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:38:52.545] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:38:58.738] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:39:04.978] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:39:11.226] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:39:17.456] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:39:23.738] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:39:29.984] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:39:36.188] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:39:42.395] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:39:48.604] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:39:54.830] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:40:01.063] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:40:07.271] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:40:13.481] ERROR: 'TeleBot' object has no attribute 'typed_middleware_handlers' | Context: Critical error in main loop
[2025-06-09 11:40:23.069] ERROR: 'dict' object has no attribute 'text' | Context: Critical error in main loop
[2025-06-09 11:44:47.942] ERROR: 'dict' object has no attribute 'text' | Context: Critical error in main loop
[2025-06-09 11:46:09.481] ERROR: 'dict' object has no attribute 'text' | Context: Critical error in main loop
[2025-06-09 11:48:53.380] ERROR: 'dict' object has no attribute 'text' | Context: Critical error in main loop
[2025-06-09 11:50:06.085] ERROR: 'dict' object has no attribute 'text' | Context: Critical error in main loop
[2025-06-09 12:19:54.460] ERROR: 'dict' object has no attribute 'text' | Context: Critical error in main loop
[2025-06-09 12:52:54.298] ERROR: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=60) | Context: Critical error in main loop
